### ISSUE TITLE
Review button and link styles and states for accessibility

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/pinecone#189]
**Describe the bug**
There are some buttons and link styles and states that are inconsistent and may pose accessibility issues. For example, some links visually appear as buttons, but are actually links. Some links and buttons have an outline when focused, while some change background colour.

These inconsistencies can create a barrier to understandability and predictability.

**Expected behavior**
Consistent visual language for focus, hover, current, visited, and active states.
Clear communication of intent of interactive elements that does not rely on colour alone.
Hover, focus, current, visited, and active states have sufficient colour contrast to adjacent colours.

Related to #188

**Comment by cherylhjli** [comment]
@jhung could you be a bit more specific about which ones are inconsistent?
Perhaps this states table could help point out the inconsistencies:
https://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/dbec8c7d-5e20-48c7-b7f2-c6366bbec4de/03-States-Table/

**Comment by cherylhjli** [comment]
As per our discussion today, changes to address this include:

- Search bar dark: focus state changed to interior double outline
- Search bar dark & light: Added hover state for input field and search button, separately
https://xd.adobe.com/view/5cbb2c96-51ce-4b66-4604-15c35058ee9c-2a8a/screen/42cf801a-3332-4bb9-89a3-6b82a4acd073/00-Desktop-components-12/
- Search bar dark - 3 colours for the dark search bar would be blue 500. dark mint 1, and blue 400 

- Desktop navigation states: Change in hover and focus state
https://xd.adobe.com/view/5cbb2c96-51ce-4b66-4604-15c35058ee9c-2a8a/screen/31e0fdb1-30b0-4ec3-82fa-96970d4c7c70/00-Desktop-components-10

- Input fields: focus state double outline on the inside of the box, rather than the outsidehttps://xd.adobe.com/view/c23a06b5-530d-4823-6e76-b968b88ad95c-b40b/screen/dbec8c7d-5e20-48c7-b7f2-c6366bbec4de/03-States-Table

**Comment by cherylhjli** [comment]
Also related to this:

- Changing "browse all resources" on the home page from a button to a link.
See the core screens v02 file for changes.

**Comment by cherylhjli** [comment]
Also related: decided on this for the resource detail page:

![Screen Shot 2020-01-30 at 2 10 30 PM](https://user-images.githubusercontent.com/9353905/73481663-4b787000-436a-11ea-9ccf-57d86c1bb6c1.png)
